import Head from 'next/head'
export default function Layout ({ children, title = 'Kevin Portofolio' }) {
    return (
      <>
        <Head>
        <title>Kevin Perea | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet"></link>
        </Head>
      <main className='no-scrollbar overflow-y-auto'>
        {children}
      </main>
    </>
  )
}