import Head from 'next/head'
export default function Layout ({ children, title = 'Kevin Portofolio' }) {
    return (
      <>
        <Head>
        <title>Kevin Perea | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/scrollreveal"></script>
      </Head>
      <main>
        {children}
      </main>
    </>
  )
}