import Head from 'next/head'
export default function Layout ({ children, title = 'Kevin Portofolio' }) {
    return (
      <>
        <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
      <main>
        {children}
      </main>
    </>
  )
}